name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 3.0
          - 2.7
          - 2.6
          - 2.5
        gemfile:
          - Gemfile-rails-7
          - Gemfile-rails-6.1
          - Gemfile-rails-6.0
        exclude:
          # Rails 7 requires Ruby 2.7+
          - ruby-version: 2.5
            gemfile: Gemfile-rails-7
          - ruby-version: 2.6
            gemfile: Gemfile-rails-7
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Run gem tests
        run: |
          bundle
          bundle exec rake
      - name: Run Rails dummy app tests
        working-directory: ./spec/dummy_app
        env:
          BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}
        run: |
          bundle
          bundle exec rake
